const data = {
  homePage: [
    {
      uniqueId: "1",
      backgroundImage: "./images/home_BackgroundPage.jpeg",
    },
  ],
  aboutPage: [
    {
      uniqueId: "1",
      backgroundImage: "./images/about_BackgroundPage.webp",
    },
  ],
  servisePage: [
    {
      uniqueId: "1",
      backgroundImage: "./images/servise_backgroundPage.jpeg",
    },
  ],
  projectPage: [
    {
      uniqueId: "1",
      backgroundImage: "./images/project_backgroundPage.jpeg",
    },
  ],
  talkToUsPage: [
    {
      uniqueId: "1",
      backgroundImage: "./images/contact_BackgroundPage.jpeg",
    },
  ],
  services: [
    {
      _id: "1",
      slag: "11",
      name: "Web Development",
      category: "Shirts",
      image: "./images/web_Development.jpeg",
      price: 100,
      countInStock: 10,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: "2",
      slag: "12",
      name: "Web & Graphic Design",
      category: "Shirts",
      image: "./images/web_design.jpeg",
      price: 100,
      countInStock: 10,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: "3",
      slag: "13",
      name: "Web Hosting",
      category: "Shirts",
      image: "./images/web_Hosting.jpeg",
      price: 100,
      countInStock: 10,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product taza",
    },
    {
      _id: "4",
      slag: "14",
      name: "IT Solution & Consultancy",
      category: "Shirts",
      image: "./images/It_consultancy.jpeg",
      price: 100,
      countInStock: 10,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
  ],

  products: [
    {
      _id: "1",
      slag: "11",
      name: "Nike Slim Shirt ",
      category: "Shirts",
      image: "./images/p1.jpg",
      price: 100,
      countInStock: 10,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },

    {
      _id: "2",
      slag: "22",
      name: "Adidas Fit Shirt ",
      category: "Shirts",
      image: "./images/p1.jpg",
      price: 120,
      countInStock: 20,
      brand: "Nike",
      rating: 4.0,
      numReviews: 10,
      description: "high quality product",
    },

    {
      _id: "3",
      slag: "33",
      name: "Lacoste Free Shirt ",
      category: "Shirts",
      image: "./images/p1.jpg",
      price: 220,
      countInStock: 0,
      brand: "Lacoste",
      rating: 4.8,
      numReviews: 17,
      description: "high quality product",
    },

    {
      _id: "4",
      slag: "44",
      name: "Nika Slim Pant",
      category: "Pants",
      image: "./images/p1.jpg",
      price: 78,
      countInStock: 15,
      brand: "Nike",
      rating: 4.5,
      numReviews: 14,
      description: "high quality product",
    },

    {
      _id: "5",
      slag: "55",
      name: "Puma Slim Pants",
      category: "Pant",
      image: "./images/p1.jpg",
      price: 65,
      countInStock: 5,
      brand: "Puma",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },

    {
      _id: "6",
      slag: "66",
      name: "Adidas Fit Pant",
      category: "Pants",
      image: "./images/p1.jpg",
      price: 139,
      countInStock: 12,
      brand: "Adidas",
      rating: 4.5,
      numReviews: 15,
      description: "high quality product",
    },
  ],
  categories: [
    {
      name: "Nike Slim Shirt",
      category: "Shirts",
      image: "/images/p1.jpg",
      price: 120,
      countInStock: 10,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      name: "Adidas Fit Shirt",
      category: "Shirts",
      image: "/images/p2.jpg",
      price: 100,
      countInStock: 20,
      brand: "Adidas",
      rating: 4.0,
      numReviews: 10,
      description: "high quality product",
    },
    {
      name: "Lacoste Free Shirt",
      category: "Shirts",
      image: "/images/p3.jpg",
      price: 220,
      countInStock: 0,
      brand: "Lacoste",
      rating: 4.8,
      numReviews: 17,
      description: "high quality product",
    },
    {
      name: "Nike Slim Pant",
      category: "Pants",
      image: "/images/p4.jpg",
      price: 78,
      countInStock: 15,
      brand: "Nike",
      rating: 4.5,
      numReviews: 14,
      description: "high quality product",
    },
    {
      name: "Puma Slim Pant",
      category: "Pants",
      image: "/images/p5.jpg",
      price: 65,
      countInStock: 5,
      brand: "Puma",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      name: "Adidas Fit Pant",
      category: "Pants",
      image: "/images/p6.jpg",
      price: 139,
      countInStock: 12,
      brand: "Adidas",
      rating: 4.5,
      numReviews: 15,
      description: "high quality product",
    },
  ],
};

export default data;
